version: "3.3"
services:  
  nginx-reverse-proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    container_name: nginx-reverse-proxy
    networks:
      - web-projects-network
networks:
  web-projects-network:
    external: true