version: "3.3"
services:  
  nginx_reverse_proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    container_name: nginx_reverse_proxy
    networks:
      - my-network
networks:
  my-network:
    external: true