# RUN
version: "3.3"
services:
  nginx_reverse_proxy:
    image: roysalazarportilla/nginx_reverse_proxy:latest
    restart: always
    ports:
      - '80:80'
    container_name: nginx_reverse_proxy
    networks:
      - my-network
networks:
  my-network:
    external: true